server:
  port: 8200
spring:
  application:
    name: arisgo-config
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/Arisgo/spring-cloud.git
#          searchPaths: repository
          searchPaths: repository/{application}
          username: arisgo@163.com
          password: zjxy26102425
#          default-label: origin/master
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://arisgo:8101/eureka,http://service:8102/eureka,http://silencer:8103/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"