server:
  port: 8102
spring:
  application:
    name: arisgo-eureka
eureka:
  instance:
    hostname: service
  client:
    serviceUrl:
      defaultZone: http://arisgo:8101/eureka,http://silencer:8103/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false