#server:
#  port: 8100
#spring:
#  application:
#    name: arisgo-eureka-server
#eureka:
#  instance:
#    hostname: arisgo
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8100/eureka
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    enable-self-preservation: false